# Generated by Django 5.2.14 on 2026-06-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_logo_to_filefield'),
        ('tickets', '0003_add_company_user_and_category'),
    ]

    operations = [
    ]
