# Generated by Django 5.2.14 on 2026-06-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_logo_to_filefield'),
        ('tickets', '0004_add_equipment'),
    ]

    operations = [
    ]
