# Generated by Django 5.2.14 on 2026-06-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_logo_to_filefield'),
        ('tickets', '0005_companyuser_is_manager'),
    ]

    operations = [
    ]
